on: push
name: Test on push
jobs:
  addComment:
    name: add comment to defect DF001268
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to aqua saas instance
        id: login
        uses: uniqueck/ga-aqua-login@v1.0.1
        env:
          AQUA_USERNAME: ${{ secrets.AQUA_USERNAME }}
          AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }}
      - name: add comment
        uses: ./
        env:
          NODE_DEBUG: http, net, stream
        with:
          aqua-token: ${{ steps.login.outputs.token }}
          defect: DF001268
          comment: "${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}"
      - name: logout to aqua saas instance
        uses: uniqueck/ga-aqua-logout@v1.0.0
        with:
          aqua-token: ${{ steps.login.outputs.token }}

